name: enerren
description: "A new Flutter project."
publish_to: "none"

version: 1.1.1+1

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  flutter_launcher_icons: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
